# Generated by Django 4.2.16 on 2024-11-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecalendar',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
